-- Create the Employee dimension table
create or replace TABLE DB_SNOWFLAKE.DATAWAREHOUSE.EMPLOYEE (
	EMPLOYEEID INTEGER(10) NOT NULL,
	FULLNAME VARCHAR(100),
	BIRTHDATE DATE,
	ADDRESS VARCHAR(250),
	primary key (EMPLOYEEID)
);

-- Create the Position dimension table
create or replace TABLE DB_SNOWFLAKE.DATAWAREHOUSE.POSITION (
	POSID INTEGER(10) NOT NULL,
	POSTITLE VARCHAR(100),
	primary key (POSID)
);

-- Create the PositionHistory fact table
-- DB_SNOWFLAKE.DATAWAREHOUSE.POSITIONHISTORY definition

create or replace TABLE DB_SNOWFLAKE.DATAWAREHOUSE.POSITIONHISTORY (
	ID NUMBER(38,0) NOT NULL,
	EMPLOYEEID INTEGER(10),
	POSID INTEGER(10),
	STARTDATE DATE,
	ENDDATE DATE,
	primary key (ID),
	foreign key (EMPLOYEEID) references DB_SNOWFLAKE.DATAWAREHOUSE.EMPLOYEE(EMPLOYEEID),
	foreign key (POSID) references DB_SNOWFLAKE.DATAWAREHOUSE.POSITION(POSID)
);

-- Create the TrainingHistory fact table
-- DB_SNOWFLAKE.DATAWAREHOUSE.TRAININGHISTORY definition
create or replace TABLE DB_SNOWFLAKE.DATAWAREHOUSE.TRAININGHISTORY (
	EMPLOYEEID INTEGER(10),
	TRAININGDATE_START DATE,
	TRAININGDATE_END DATE,
	TRAININGNAME VARCHAR(250),
	TRAININGDURATION NUMBER(38,0),
	TRAININGLOCATION VARCHAR(250)
	foreign key (EMPLOYEEID) references DB_SNOWFLAKE.DATAWAREHOUSE.EMPLOYEE(EMPLOYEEID)
);
